version: '3'
services:
  web:
    build: .
    ports:
     - "8080:80"





































# version: '3'
# services:
#   web:
#     build: .
#     ports:
#      - "8080:80"
#   nginx:
#     image: nginx:alpine
#     container_name: nginx-app
#     volumes:
#     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#     ports:
#     - 80:80
#     depends_on:
#     - web

